version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9091:9090

    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true

  grapana:
    image: grafana/grafana:11.3.1
    container_name: grafana

    ports:
      - 3001:3000

    links:
      - prometheus